### ISSUE TITLE
Issues with reconstruction of shiny ball scene

### ISSUE THREAD

**Issue by gkouros** [half-potato/nmf#10]
Hi. I'm trying to reproduce the results of the paper and it has worked out pretty well on most scenes of the shiny-blender dataset but it still keeps failing in the shiny ball scene. Do you have any idea why? I used the default settings in [configs/dataset/ball.yaml](https://github.com/half-potato/nmf/blob/main/configs/dataset/ball.yaml).

Below you can see the result with field.smoothing=0.5 and field.smoothing=1.0 (as suggested in https://github.com/half-potato/nmf/issues/7):
![image](https://github.com/half-potato/nmf/assets/9272795/40f64a5d-fe8b-47ce-9d8c-2b17933f4cb4)

![image](https://github.com/half-potato/nmf/assets/9272795/2bc2cdb2-44f5-400a-9a7c-43ddcba604d2)

**Comment by half-potato** [comment]
Try dataset.aabb_scale=2

**Comment by gkouros** [comment]
Thanks! That worked perfectly!
