### ISSUE TITLE
How to train with known envmap?

### ISSUE THREAD

**Issue by gkouros** [half-potato/nmf#11]
Hi,

Is it possible to train with a known envmap and if so, how can you do that? I'm trying to see how the model performs with regard to material estimation if you reduce the ambiguity by providing known illumination.

I tried to set the fixed_bg argument but it's not working. It seems to expect a torch checkpoint and when I feed it with the _backgrounds/forest.th_  there are some conflicts with resolution (which is easy to fix) and missing keys (not so easy to fix).

Also, is it possible to use the exr files directly?

Thanks.

**Comment by half-potato** [comment]
You probably need to recreate the environment map checkpoint. It's probably from an older version of the code.
```
python -m scripts.pano2cube backgrounds/forest.exr --output backgrounds/forest.th
```

If this is not the case, can you send the list of missing keys? There is a chance you can just skip those keys with strict=false.

**Comment by gkouros** [comment]
It seems there is an issue with my version of imageio (2.31.6):
```
ValueError: Could not load bitmap "/path/to/nmf/backgrounds/forest.exr": Cannot read image file "". Unknown compression type in image header.
```
Switching to opencv for reading the exr file works. 

Also, failing to import  bg_modules, but that can just be removed since it's not used anymore.

Envmap supervision seems to be running fine after recreating _forest.th_.

**Comment by half-potato** [comment]
Good to hear things are working.

**Comment by gkouros** [comment]
Is it normal to get worse performance with the GT envmap? I get around 2 PSNR less on the shiny-blender/car scene in this case.

**Comment by half-potato** [comment]
I suspect that you need to start with a low frequency environment map and steadily increase the frequency through training. Just a hunch though.
