### ISSUE TITLE
Question about batch size

### ISSUE THREAD

**Issue by gkouros** [half-potato/nmf#12]
Hi.

I see that in the main training loop you use a varying batch size, rather than a fixed one. Can you please explain the rationale behind this decision and how the update rule works? 

Thanks.

**Comment by half-potato** [comment]
It's the same thing NerfAcc does. The idea is to maximize the batch size while limiting the number of ray samples so you don't run out of memory.

**Comment by gkouros** [comment]
Ok. Thanks for the explanation.
