### ISSUE TITLE
Regarding the relighting evaluation

### ISSUE THREAD

**Issue by dehezhang2** [half-potato/nmf#17]
May I ask where you get the ground truth images for relighting metrics evaluation for shiny blender dataset? Could you please provide the relighting dataset, or provide the way to generate the relighting evaluation dataset?

**Comment by gkouros** [comment]
You can download the shiny blender models from the webpage of [Ref-NeRF](https://dorverbin.github.io/refnerf/). Then you simply regenerate the datasets with different HDRI images to get the relighted ground truth. I think all the used HDRIs are already in blender by default.

**Comment by dehezhang2** [comment]
> You can download the shiny blender models from the webpage of [Ref-NeRF](https://dorverbin.github.io/refnerf/). Then you simply regenerate the datasets with different HDRI images to get the relighted ground truth. I think all the used HDRIs are already in blender by default.

Thanks for your quick reply. And in terms of regeneration, did you use blender nerf or other scripts?

**Comment by gkouros** [comment]
One of those scripts yes, I don't remember which one exactly, but to generate the exact same poses I had to import the json file from the original shiny blender dataset, since I couldn't find an analytical method instead.

**Comment by gkouros** [comment]
I haven't done any such evaluation for my project yet. Ask @half-potato.

**Comment by half-potato** [comment]
Yes. It is reasonably high frequency.

**Comment by half-potato** [comment]
I used the original blend files, replaced the background, and rerendered them. I’ll ask for permission to release the dataset.

**Comment by half-potato** [comment]
Hopefully this helps:
https://drive.google.com/file/d/131eN_Kfo-_-TOPwWjCyc02KjyOTY7bxR/view?usp=sharing

**Comment by dehezhang2** [comment]
> Hopefully this helps: https://drive.google.com/file/d/131eN_Kfo-_-TOPwWjCyc02KjyOTY7bxR/view?usp=sharing

Thanks for sharing the dataset!

**Comment by dehezhang2** [comment]
May I also ask how you evaluated the relighting for nvdiffrec and nvdiffrecmc? Did you use the blender script or change their environment map during relighting?

**Comment by half-potato** [comment]
I used a blender script to rerender things with a new environment map.
