### ISSUE TITLE
Question about roughness

### ISSUE THREAD

**Issue by gkouros** [half-potato/nmf#18]
https://github.com/half-potato/nmf/blob/3f97cd3dd81e5a558499cdaa628382122afad087/models/microfacet.py#L360
Shouldn't the key be "r2" instead of "r1"? Is that a bug or is there a reason behind this?

Also, what do r1 and r2 correspond to? They are the output of the roughness MLP but roughness is usually scalar, so what do the two values correspond to?

Thank you in advance!

**Comment by half-potato** [comment]
Dear George,
The reason there are 2 roughness values is because I originally wanted to handle anisotropic materials, but I ended up only handling isotropic ones. As a result, I regressed two, but set both to be the same.

**Comment by gkouros** [comment]
Ok. Makes sense now. Thanks for the quick response!
