### ISSUE TITLE
Lower performance after loading the model for evaluation

### ISSUE THREAD

**Issue by gkouros** [half-potato/nmf#21]
As the title suggests, there are some inconsistencies between the evaluation at the end of training and the evaluation after loading the saved model. See the below image as an example. Geometry and materials are the same but the rendering of the reflections is different. Is there something that's not stored in the saved checkpoints or not loaded properly that comes to mind? Or something not being initialized correctly?

The metrics are as follows:
|                                    | PSNR | SSIM | LPIPS | MAE |
|------------------------------------|------|------|-------|-----|
| Initial evaluation after training  | 29.9   | 0.949     |  0.035     |  7.843   |
| Reevaluation with loaded model     |  29.72   |  0.949    |0.034       |  7.843   |

Thank you in advance!

![temp](https://github.com/half-potato/nmf/assets/9272795/7596018f-7c50-4149-bfde-3ad7e3f2e48a)

**Comment by half-potato** [comment]
Looks like it probably has something to do with what rays are traced back through the model. It might be (max_retrace_rays)[https://github.com/half-potato/nmf/blob/69f176f370f65aaae0edfbe113904062e7e857c6/models/microfacet.py#L65C9-L65C30]. Try setting this higher?

**Comment by gkouros** [comment]
|                                    | PSNR | SSIM | LPIPS | MAE |
|------------------------------------|------|------|-------|-----|
| Initial evaluation after training  | 29.9   | 0.949     |  0.035     |  7.843   |
| Reevaluation with loaded model     |  29.72   |  0.949    |0.034       |  7.843   |

**Comment by gkouros** [comment]
Increasing max_retrace_rays to 8k seems to reach the original performance, but any idea why this happens? Isn't max_retrace_rays set to 1000 during training and evaluation? Why is there such a large difference in reevaluation? 

| max_retrace_rays                                   | PSNR | SSIM | LPIPS | MAE |
|------------------------------------|------|------|-------|-----|
|  Orig | 29.9   | 0.949     |  0.035     |  7.843   |
| 1000     |  29.72   |  0.949    |0.034       |  7.843   |
| 2000     |  29.76   |  0.949    |0.034       |  7.843   |
| 4000     |  29.81   |  0.949    |0.034       |  7.843   |
| 8000     |  29.9   |  0.949    |0.034       |  7.843   |
| 20000     |  30.00   |  0.949    |0.034       |  7.843   |

**Comment by half-potato** [comment]
The number of max_retrace_rays changes dynamically throughout training to avoid OOM issues.

**Comment by gkouros** [comment]
Ok, thanks! This solves my problem.
