### ISSUE TITLE
question about Appendix B

### ISSUE THREAD

**Issue by Lingyun0109** [half-potato/nmf#22]
Could you please tell me which part of the main text and code corresponds to the “neural shading work h” in Appendix B of the paper? I didn’t quite understand this section.

**Comment by half-potato** [comment]
I believe this is the corresponding section: https://github.com/half-potato/nmf/blob/7c79de00d111b5fdc0a6d0af2a9c00ee63bacb0f/models/microfacet.py#L596

**Comment by Lingyun0109** [comment]
> I believe this is the corresponding section:
> 
> https://github.com/half-potato/nmf/blob/7c79de00d111b5fdc0a6d0af2a9c00ee63bacb0f/models/microfacet.py#L596

thank you! I’ll go take a closer look
