### ISSUE TITLE
[Question] About the derivation of normal vector from the density field

### ISSUE THREAD

**Issue by costrice** [half-potato/nmf#4]
In the released paper _Neural Microfacet Fields for Inverse Rendering_ (ICCV'23), it was mentioned in Section C of the appendix that

> To calculate the normal vectors of the density field, we apply a finite difference kernel, convolved with a 3×3 Gaussian smoothing kernel with σ = 1, then linearly interpolate between samples to get the resulting gradient in the 3D volume.

I appreciate this idea to use smoothed gradient as the shading normal, and want to check the code that implements it. 
However, I failed to find the code that implements this finite difference and gaussian filtering functionality.

The `forward` method of the `TensorNeRF` class in `modules/tensor_nerf.py` [seems to be using](https://github.com/half-potato/nmf/blob/main/modules/tensor_nerf.py#L393)  the [`compute_normals` method](https://github.com/half-potato/nmf/blob/main/fields/tensor_base.py#L107) of the `TensorBase` class, but this method directly use analytically derived gradients, rather than gradients from finite difference, without doing Gaussian filtering.

Then, I searched the project for 'normal' and found [another function](https://github.com/half-potato/nmf/blob/main/fields/triplanar.py#L101) called `compute_density_norm` in `fields/triplanar.py` that seems doing finite difference (I'm not sure). But this class seems to be not in active use.

I would be very grateful if the authors could refer me to the code implementing the normal derivation described in the paper. Thanks in advance!

**Comment by half-potato** [comment]
The gradient calculation can be found here: modules/grid_sample_Cinf.py

This special grid sample operator is used here: fields/tensoRF.py

**Comment by costrice** [comment]
Thanks very much for your immediate and helpful reply!
