### ISSUE TITLE
[Question] Reproduction of the reported scores in the paper

### ISSUE THREAD

**Issue by ChemJeff** [half-potato/nmf#5]
Hi, I have recently found this excellent work and tried a demo with _car_ scene from the _Shiny Blender_ dataset. However, the resulting evaluation scores are lower (with a large margin) than reported in the paper (v2 on arXiv):
    PSNR: **29.61** (this score from the saved `mean.txt`; in the paper: **30.28**)
    SSIM: **0.9448** (this score from the saved `mean.txt`; in the paper: **0.951**)
    MAE: **8.0223** (this score calculated on _saved normal maps_; in the paper: **2.598**)

The command I used:
`python train.py -m expname=EXPNAME model=microfacet_tensorf2 dataset=car vis_every=5000 datadir=DATADIR model.arch.bg_module.bg_path=backgrounds/forest.exr`

I hope to hear your response soon, thanks.

**Comment by half-potato** [comment]
Currently investigating the cause of this weird extra bit under the car. Not sure when this started happening...
![image](https://github.com/half-potato/nmf/assets/3977802/027c003f-dfcb-47a9-9a70-b94cd8f5e314)

**Comment by half-potato** [comment]
Turns out the default config was incorrect. The fresnel mixing mode should be set to fresnel, not lambda.
